name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    paths:
    - markdown_generator/**

permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v5
      - name: instal pandas
        run: pip install pandas
      - name: execute py script # run file
        run: |
          python publications.py
          python service.py
        working-directory: markdown_generator
      - name: Commit report
        run: |
          git config --global user.name 'Nathan Cassee'
          git config --global user.email 'TheDutchDevil@users.noreply.github.com'
          git commit -am "Generate markdown files"
          git push